<h2>Create User</h2>

<?php echo $this->getContent(); ?>

<form method="post" action="create">
  <div class="form-group">
    <label for="username">User Nmae</lable>
      <input type="text" id="username" name="username">
  </div>
  <div class="form-group">
    <label for="email">Email</lable>
      <input type="text" id="email" name="email">
  </div>
  <div class="form-group">
    <label for="password">Password</lable>
      <input type="password" id="password" name="password">
  </div>
  <div class="form-group">
      <input type="submit" name="submit" value="Submit">
  </div>
</form>
