<?php echo $this->getContent();?>
<form action="login/login" method="post">
  <div class="form-control">
    <label for="username">Username</label>
    <input type="text" id='username' name="username">
  </div>
  <div class="form-control">
    <label for="password">Password</label>
    <input type="password" id='password' name="password">
  </div>
  <div class="form-control">
    <input type="submit" name="submit" value="Login">
  </div>
</form>
